image: docker:latest

variables:
    DOCKER_DRIVER: overlay
    CURRENT_DIRECTORY: ${CI_PROJECT_DIR}

service:
- docker:dind

before_script:
- docker info
- docker pull asciidoctor/docker-asciidoctor
- docker pull stevvooe/pdftk
- mkdir output

build:
    stage: build
    script:
    - ./build-ci.sh
    artifacts:
    - output/
