sudo: required

language: ruby

services:
    - docker

before_install:
    - mkdir output
    - docker pull asciidoctor/docker-asciidoctor
    - docker pull stevvooe/pdftk

env:
    - CURRENT_DIR=$TRAVIS_BUILD_DIR

script:
    - build-ci.sh

after_failure:
    - docker logs asciidoc-to-html
    - docker logs asciidoc-to-pdf-whole
    - docker logs asciidoc-to-pdf-last
    - docker logs asciidoc-to-epub
    - docker logs asciidoc-to-epub

after_error:
    - docker logs asciidoc-to-html
    - docker logs asciidoc-to-pdf-whole
    - docker logs asciidoc-to-pdf-last
    - docker logs asciidoc-to-epub
    - docker logs asciidoc-to-epub

after_success:
    - cd output; cp ../images images
    - git init
    - git config user.name "${GH_USER_NAME}"
    - git config user.email "${GH_USER_EMAIL}"
    - git add .;
    - git commit -m 'Deploy to gh-pages'
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1